### ISSUE TITLE
First save after "Save and Continue" routes away from current record

### ISSUE THREAD

**Issue by emlunde** [EAVFW/EAVFW#54]
Setup for issue: After pressing "Gem og fortsæt" (Save and continue) from a record, the record is saved correctly and you are moved away to the "new entity" page, where you can create a new record.

Problem:
After the first save on the new record the record is saved properly but a new record page is opened again.

Expectation:
After the first save on the new record we stay on the current and now saved new record instead of opening another new page of an empty record.

**Comment by pksorensen** [comment]
@magesoe  - i dont expect this impact you guys, but we fixed this and moving it to dev.
